### ISSUE TITLE
Drop @expectedException in favour of self::expectException

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/disco#108]
There are a bunch of `@expectedException*` annotations left in the unit tests which should be replaced by the corresponding `self::expectException*()` method calls due to being "[a new best practice](https://thephp.cc/news/2016/02/questioning-phpunit-best-practices)" as well as for consistency reasons.

**Comment by shochdoerfer** [comment]
@SenseException mind helping with this?

**Comment by SenseException** [comment]
I can do that.
