### ISSUE TITLE
Check if Disco can be installed on PHP 7.2 and latest ProxyManager version

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/disco#111]
Make sure that the current version of Disco can be installed on PHP 7.2. Also check for side-effects with the latest version of ProxyManager which is focused [PHP 7.2 only](https://twitter.com/Ocramius/status/931302230946435072?s=09).

**Comment by SenseException** [comment]
Will the Composer constraint be updated to 7.2 too or will the minimum version stay on 7.1?

**Comment by shochdoerfer** [comment]
Of course Disco should be migrated to PHP 7.2. Since it is out for a while we can tackle that issue now. Want to provide a PR?

**Comment by SenseException** [comment]
Update to PHP 7.2 as minimum version and to the constraint fitting ProxyManager version. I'll take a look at that.

**Comment by shochdoerfer** [comment]
I would assume it's mostly adding `void` here and there. IIRC Marco told he had not changed much between both versions.

**Comment by SenseException** [comment]
Nothing seems in need to be added with the latest version of ProxyManager. The tests are still working. I'll provide an PR for a php 7.2 as minimum.
