### ISSUE TITLE
Remove phing dependency, replace with composer scripts

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/disco#126]
Given we don't use complex logic in our build.xml, we could easily migrate to composer scripts and drop "just another" dev dependency from the project.

We'd simply need to manually install [security-checker](https://github.com/sensiolabs/security-checker) as the tool is not yet installable via [PHIVE](https://phar.io).

**Comment by heiglandreas** [comment]
See https://github.com/bitExpert/disco/issues/125#issuecomment-431650771. The security-checker would then be installable via the same tool as all the others...

**Comment by shochdoerfer** [comment]
Fixed with #136
