### ISSUE TITLE
PHP7 type check problem

### ISSUE THREAD

**Issue by msphn** [bitExpert/disco#44]
If strict_types=1 you can set types like string in function signature.

Seems like these types are removed while compilation resulting in following error:
PHP Warning:  Declaration of ProxyManagerGeneratedProxy__PM__\src\company\application\Config\Generateda2fc343f86910958b2805ad36ffa91cc::application($sessionSecret = NULL) should be compatible with src\company\application\Config::application(string $sessionSecret = NULL) in /vagrant/api/cache/di/ProxyManagerGeneratedProxy__PM__srccompanyapplicationConfigGenerateda2fc343f86910958b2805ad36ffa91cc.php on line 314

**Comment by msphn** [comment]
@shochdoerfer not a problem in disco!
https://github.com/Ocramius/ProxyManager/issues/300

Seems to be an issue in our version of proxymanager which is fixed in later version.

**Comment by msphn** [comment]
ProxyManager 2.0.\* does require PHP7 update would raise disco PHP7 requirements as well

**Comment by shochdoerfer** [comment]
Yes this is why we haven't upgraded the dependency yet. Some more changes are required for that. Disco works fine with PHP 7 but typehints are not yet considered.

**Comment by shochdoerfer** [comment]
Feel free to add feature request for PHP 7 strict support, or better start working on a PR ;)
