### ISSUE TITLE
Improve README file

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/disco#70]
Optimize the README.md file to make it easier for beginners to get started. In addition I would love to see the following changes:
- add a rationale to explain why Disco makes sense and why/how it is different to the other DI containers in PHP
- highlight the different use-cases that can be solved with Disco
- highlight the different ways of injecting dependencies e.g. constructor injection, setter injection, interface injection
- improve the documentation of the bean configuration settings and how they affect each other
- fix some typos ;)

**Comment by SenseException** [comment]
Maybe this issue could be extended to other documentation parts of the project like the contributors-guide. It mentions a `develop` branch that seems to be not existent anymore.

**Comment by shochdoerfer** [comment]
Good catch. We do not use a develop branch, so far. Mind sending a PR to update the contribution guide?

**Comment by SenseException** [comment]
Sorry, not in the near future :-(. But something different will be ready for a PR soon.

**Comment by shochdoerfer** [comment]
The hints regarding the "develop" branch got removed via #91.

**Comment by shochdoerfer** [comment]
Fixed with #82.
