### ISSUE TITLE
Add bitexpert/phing-securitychecker to the build process

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/disco#72]
To make sure that there are no security issues open for the dependencies used by Disco rely on the [SensioLabs Security Advisories Checker](https://security.sensiolabs.org). Since we use Phing for the build it makes the most sense to add the [bitexpert/phing-securitychecker](https://github.com/bitExpert/phing-securitychecker) package and include it in the build.xml file.

**Comment by skoop** [comment]
I believe this can be closed as `already done`: Security checker is already installed in this project since Nov 11, 2015, from what I can gather. See also: https://github.com/bitExpert/disco/commit/d2b256a12a51349791d8d0997c7a38942a7ed45b

**Comment by shochdoerfer** [comment]
Thanks for pointing out @skoop. I quickly scanned over the composer.json and completely missed that the dependency is already there. Feel free to pick one of the other open isses then ;)
