### ISSUE TITLE
Insufficient boolean cast for @Parameter required attribute

### ISSUE THREAD

**Issue by dropdevcoding** [bitExpert/disco#84]
Currently the ```@Parameter "required" option``` is casted to boolean via ```(bool)``` internally, while the ```@Bean "lazy" option ``` is casted via a dedicated method called ```parseBooleanValue```.

This leads to the inconvenience that you only may use "required"="0" since 0 as string gets casted correctly to false while "false" will result in true.

Solution suggestion: 

Use an ```AnnotationAttributeParser``` which contains the method ```parseBooleanValue``` as static method and use it in the Bean annotation and Parameter Annotation

Hint: For testing you will have to clear the cache files after each configuration change to get the correct results.

**Comment by shochdoerfer** [comment]
Good catch. Thanks!
