### ISSUE TITLE
Rising Code Coverage for Disco

### ISSUE THREAD

**Issue by SenseException** [bitExpert/disco#94]
Currently, Disco has a code coverage of ~95%, but most of its coverage happened by hardcoded instance creations over `bitExpert\Disco\AnnotationBeanFactory` and `bitExpert\Disco\AnnotationBeanFactoryUnitTest`. In case of possible refactorings, does it make sense to add coverage by testing every class' methods separated in custom unit tests? 

### And why 100% code coverage?

I started to take a look into the uncovered code and asked myself if there may be unreachable code by writing tests.

For example: https://github.com/bitExpert/disco/blob/v0.8.0/src/bitExpert/Disco/BeanFactoryConfiguration.php#L146

``` php
if (!spl_autoload_register($this->proxyAutoloader, false)) {
    throw new RuntimeException(
        sprintf('Cannot register autoloader "%s"', get_class($this->proxyAutoloader))
    );
}
```

`spl_autoload_register` can return false in cases of an error, like using a function name, that doesn't exist, in form of a string, but I didn't find a way to make this fail with a callable autoloader class using `__invoke()`. I haven't try the same for `spl_autoload_unregister` yet, but I expect the same like in `spl_autoload_register`.

**Comment by shochdoerfer** [comment]
Thanks for your feedback. As for the test organization I am up for new ideas. Test classes per method might not make sense for the `AnnotationBeanFactory` as it has only two methods. A better approach might be to create test classes per configuration type, e.g. one test class for singleton instance creations, one for the prototype instance creations and so on.

As for the uncovered code you are right, this mostly is code that is hard to test, like the example you mentioned with the failing `spl_autoload_register` function. Do you recommend to remove the if statement even though the PHP manual mentions that the function could potentially return false? 
A work-a-round for this particular case might be to get rid of the second method parameter which indicates that `spl_autoload_register` itself does not throw an exception.

**Comment by SenseException** [comment]
For the organization of tests, my suggestion was the classic "test class for a class" for unit tests. I like your idea for `AnnotationBeanFactory` to separate per configuration type. I haven't checked all the possibilities of the configuration yet, so I'm currently unaware of further uncovered config-combinations.

The error case for `spl_autoload_register` is from a time where the argument can be invalid like a unknown function name as string or a callback. Because of the used interface and its implementation of `__invoke()`, I don't see a way to get into the previous mentioned if-block. The same with `exception = true`. You'll get the exception in the same way as depending on the return value. I haven't found a way to make `spl_autoload_register` fail in Disco, but if that's impossible to achieve, the if-blocks can be removed.

I also have a question about the `is_writable` checks that aren't tested yet. It is just used in one place in Disco, so I wouldn't introduce vfsStream for just one case. Do you have a suggestion for another way to cover the `is_writable` if-block for [this test](https://github.com/SenseException/disco/blob/coverage/tests/bitExpert/Disco/BeanFactoryConfigurationUnitTest.php#L122)?

**Comment by shochdoerfer** [comment]
Looks like we can get rid of the exception handling for the `spl_autoload_register` and the `spl_autoload_unregister`. I checked the php source code to figure out when the exceptions are thrown. As it looks to me, you are right those edge-cases can be ignored in our setup.

I do not see an issue adding vfsStream as a dev dependency. We might be able to use it in a few other test cases as well. Currently all cache files are written to the system default temp directory, we could use a vfsStream resource instead and extend the tests to check if the files got written as well.

**Comment by shochdoerfer** [comment]
For restructuring the `AnnotationBeanFactory` tests, I would distinguish between lazy and non-lazy dependencies, that is what we do in the [BeanMethod generator](https://github.com/bitExpert/disco/blob/master/src/bitExpert/Disco/Proxy/Configuration/MethodGenerator/BeanMethod.php#L75) as well. Other than that you would need to distinguish between session-aware and singleton/non-singleton options.

**Comment by SenseException** [comment]
Thank you for your feedback. I'll add vfsStream as a dev dependency, remove the autoload-functions exception and add new coverage.

**Comment by SenseException** [comment]
I found some time to work on the code coverage again. I'll split this into two PRs: One doing the last pieces of coverage and another one for creating the class coverage by unit tests instead by `AnnotationBeanFactory`.

**Comment by shochdoerfer** [comment]
Makes sense. Smaller changes are always good. Thanks.
